#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brada3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Brada")]
	public partial class BradaDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertitem_order(item_order instance);
    partial void Updateitem_order(item_order instance);
    partial void Deleteitem_order(item_order instance);
    partial void InsertTablePlace(TablePlace instance);
    partial void UpdateTablePlace(TablePlace instance);
    partial void DeleteTablePlace(TablePlace instance);
    partial void InsertTbl_Casheir_Sale(Tbl_Casheir_Sale instance);
    partial void UpdateTbl_Casheir_Sale(Tbl_Casheir_Sale instance);
    partial void DeleteTbl_Casheir_Sale(Tbl_Casheir_Sale instance);
    partial void InsertTbl_Daily_operation(Tbl_Daily_operation instance);
    partial void UpdateTbl_Daily_operation(Tbl_Daily_operation instance);
    partial void DeleteTbl_Daily_operation(Tbl_Daily_operation instance);
    partial void InsertTbl_Import(Tbl_Import instance);
    partial void UpdateTbl_Import(Tbl_Import instance);
    partial void DeleteTbl_Import(Tbl_Import instance);
    partial void InsertTBL_Item_Price(TBL_Item_Price instance);
    partial void UpdateTBL_Item_Price(TBL_Item_Price instance);
    partial void DeleteTBL_Item_Price(TBL_Item_Price instance);
    partial void InsertTbl_login(Tbl_login instance);
    partial void UpdateTbl_login(Tbl_login instance);
    partial void DeleteTbl_login(Tbl_login instance);
    partial void InsertTBL_Number(TBL_Number instance);
    partial void UpdateTBL_Number(TBL_Number instance);
    partial void DeleteTBL_Number(TBL_Number instance);
    partial void InsertTbl_Order(Tbl_Order instance);
    partial void UpdateTbl_Order(Tbl_Order instance);
    partial void DeleteTbl_Order(Tbl_Order instance);
    partial void InsertTBL_Receive(TBL_Receive instance);
    partial void UpdateTBL_Receive(TBL_Receive instance);
    partial void DeleteTBL_Receive(TBL_Receive instance);
    partial void InsertTblAddItem(TblAddItem instance);
    partial void UpdateTblAddItem(TblAddItem instance);
    partial void DeleteTblAddItem(TblAddItem instance);
    partial void InsertTBLCheck(TBLCheck instance);
    partial void UpdateTBLCheck(TBLCheck instance);
    partial void DeleteTBLCheck(TBLCheck instance);
    partial void InsertTblItem(TblItem instance);
    partial void UpdateTblItem(TblItem instance);
    partial void DeleteTblItem(TblItem instance);
    partial void InsertTBLTable(TBLTable instance);
    partial void UpdateTBLTable(TBLTable instance);
    partial void DeleteTBLTable(TBLTable instance);
    partial void InsertTBLCoffee(TBLCoffee instance);
    partial void UpdateTBLCoffee(TBLCoffee instance);
    partial void DeleteTBLCoffee(TBLCoffee instance);
    partial void InsertTBLRestaurant(TBLRestaurant instance);
    partial void UpdateTBLRestaurant(TBLRestaurant instance);
    partial void DeleteTBLRestaurant(TBLRestaurant instance);
    partial void InsertTBLSea(TBLSea instance);
    partial void UpdateTBLSea(TBLSea instance);
    partial void DeleteTBLSea(TBLSea instance);
    partial void InsertTblShlal(TblShlal instance);
    partial void UpdateTblShlal(TblShlal instance);
    partial void DeleteTblShlal(TblShlal instance);
    #endregion
		
		public BradaDataClassesDataContext() : 
				base(global::Brada3.Properties.Settings.Default.BradaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public BradaDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BradaDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BradaDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BradaDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<item_order> item_orders
		{
			get
			{
				return this.GetTable<item_order>();
			}
		}
		
		public System.Data.Linq.Table<TablePlace> TablePlaces
		{
			get
			{
				return this.GetTable<TablePlace>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Casheir_Sale> Tbl_Casheir_Sales
		{
			get
			{
				return this.GetTable<Tbl_Casheir_Sale>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Daily_operation> Tbl_Daily_operations
		{
			get
			{
				return this.GetTable<Tbl_Daily_operation>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Import> Tbl_Imports
		{
			get
			{
				return this.GetTable<Tbl_Import>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Item_Price> TBL_Item_Prices
		{
			get
			{
				return this.GetTable<TBL_Item_Price>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_login> Tbl_logins
		{
			get
			{
				return this.GetTable<Tbl_login>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Number> TBL_Numbers
		{
			get
			{
				return this.GetTable<TBL_Number>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Order> Tbl_Orders
		{
			get
			{
				return this.GetTable<Tbl_Order>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Receive> TBL_Receives
		{
			get
			{
				return this.GetTable<TBL_Receive>();
			}
		}
		
		public System.Data.Linq.Table<TblAddItem> TblAddItems
		{
			get
			{
				return this.GetTable<TblAddItem>();
			}
		}
		
		public System.Data.Linq.Table<TBLCheck> TBLChecks
		{
			get
			{
				return this.GetTable<TBLCheck>();
			}
		}
		
		public System.Data.Linq.Table<TblItem> TblItems
		{
			get
			{
				return this.GetTable<TblItem>();
			}
		}
		
		public System.Data.Linq.Table<TBLTable> TBLTables
		{
			get
			{
				return this.GetTable<TBLTable>();
			}
		}
		
		public System.Data.Linq.Table<TBLCoffee> TBLCoffees
		{
			get
			{
				return this.GetTable<TBLCoffee>();
			}
		}
		
		public System.Data.Linq.Table<TBLRestaurant> TBLRestaurants
		{
			get
			{
				return this.GetTable<TBLRestaurant>();
			}
		}
		
		public System.Data.Linq.Table<TBLSea> TBLSeas
		{
			get
			{
				return this.GetTable<TBLSea>();
			}
		}
		
		public System.Data.Linq.Table<TblShlal> TblShlals
		{
			get
			{
				return this.GetTable<TblShlal>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.del")]
		public int del([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> _id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), _id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateproduct3")]
		public int updateproduct3([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_new, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string newname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> newquantity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> newQuantity_Part_Num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> newcostprice, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> newtotalcost, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> newValidationdate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_new, newname, newquantity, newQuantity_Part_Num, newcostprice, newtotalcost, newValidationdate);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.del_tbl_num")]
		public int del_tbl_num([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.delin_Daily_OPeration")]
		public int delin_Daily_OPeration([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ins_item_order")]
		public int ins_item_order([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> itemid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> o_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> total_cost, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> d, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tbl_num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> disc_val, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> tax, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> finalcost, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string pay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, itemid, o_id, total_cost, d, tbl_num, disc_val, tax, finalcost, pay);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ins_item_order1")]
		public int ins_item_order1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> itemid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> o_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> total_cost, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> d, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tbl_num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> disc_val, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> tax, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> finalcost, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string pay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, itemid, o_id, total_cost, d, tbl_num, disc_val, tax, finalcost, pay);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ins_tbl_num")]
		public int ins_tbl_num([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tblid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> place_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, tblid, num, place_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insert_Daily_Operation")]
		public int insert_Daily_Operation([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> newItem_Code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string new_ITem_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> quantit_Num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> packu_price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> totalcost, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> import_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> receipt_Code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i, newItem_Code, new_ITem_Name, quantit_Num, packu_price, totalcost, import_date, receipt_Code);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insert_tbl_Import")]
		public int insert_tbl_Import([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> new_receipt_code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> new_import_date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i, new_receipt_code, new_import_date);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insert_tbl_Item2", IsComposable=true)]
		public object insert_tbl_Item2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(60)")] string new_ITem_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> quantit_Num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> packu_price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pieces_num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> quantity_int, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> totalcost, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quantity_Int_Price", DbType="Int")] System.Nullable<int> quantity_Int_Price)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), new_ITem_Name, quantit_Num, packu_price, pieces_num, quantity_int, date, totalcost, quantity_Int_Price).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insert_tbllogin")]
		public int insert_tbllogin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hint)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, pass, hint);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.report_item_order")]
		public ISingleResult<report_item_orderResult> report_item_order([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> o_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), o_id);
			return ((ISingleResult<report_item_orderResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.report_order_details")]
		public ISingleResult<report_order_detailsResult> report_order_details([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> or_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), or_id);
			return ((ISingleResult<report_order_detailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.report_tbl_num")]
		public ISingleResult<report_tbl_numResult> report_tbl_num([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> o_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), o_id);
			return ((ISingleResult<report_tbl_numResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.selectall")]
		public ISingleResult<selectallResult> selectall([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> d)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), d);
			return ((ISingleResult<selectallResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ins_order")]
		public int ins_order([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> or_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> item_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> count, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> price)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, or_id, item_id, count, price);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.item_order")]
	public partial class item_order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _item_id;
		
		private int _order_id;
		
		private double _total_cost;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _TBL_Num;
		
		private System.Nullable<double> _discount_val;
		
		private System.Nullable<double> _Tax_val;
		
		private System.Nullable<double> _final_cost;
		
		private string _payment;
		
		private EntityRef<Tbl_Order> _Tbl_Order;
		
		private EntityRef<TblItem> _TblItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onitem_idChanging(int value);
    partial void Onitem_idChanged();
    partial void Onorder_idChanging(int value);
    partial void Onorder_idChanged();
    partial void Ontotal_costChanging(double value);
    partial void Ontotal_costChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnTBL_NumChanging(System.Nullable<int> value);
    partial void OnTBL_NumChanged();
    partial void Ondiscount_valChanging(System.Nullable<double> value);
    partial void Ondiscount_valChanged();
    partial void OnTax_valChanging(System.Nullable<double> value);
    partial void OnTax_valChanged();
    partial void Onfinal_costChanging(System.Nullable<double> value);
    partial void Onfinal_costChanged();
    partial void OnpaymentChanging(string value);
    partial void OnpaymentChanged();
    #endregion
		
		public item_order()
		{
			this._Tbl_Order = default(EntityRef<Tbl_Order>);
			this._TblItem = default(EntityRef<TblItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_id", DbType="Int NOT NULL")]
		public int item_id
		{
			get
			{
				return this._item_id;
			}
			set
			{
				if ((this._item_id != value))
				{
					if (this._TblItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onitem_idChanging(value);
					this.SendPropertyChanging();
					this._item_id = value;
					this.SendPropertyChanged("item_id");
					this.Onitem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int NOT NULL")]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					if (this._Tbl_Order.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onorder_idChanging(value);
					this.SendPropertyChanging();
					this._order_id = value;
					this.SendPropertyChanged("order_id");
					this.Onorder_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_cost", DbType="Float NOT NULL")]
		public double total_cost
		{
			get
			{
				return this._total_cost;
			}
			set
			{
				if ((this._total_cost != value))
				{
					this.Ontotal_costChanging(value);
					this.SendPropertyChanging();
					this._total_cost = value;
					this.SendPropertyChanged("total_cost");
					this.Ontotal_costChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBL_Num", DbType="Int")]
		public System.Nullable<int> TBL_Num
		{
			get
			{
				return this._TBL_Num;
			}
			set
			{
				if ((this._TBL_Num != value))
				{
					this.OnTBL_NumChanging(value);
					this.SendPropertyChanging();
					this._TBL_Num = value;
					this.SendPropertyChanged("TBL_Num");
					this.OnTBL_NumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_val", DbType="Float")]
		public System.Nullable<double> discount_val
		{
			get
			{
				return this._discount_val;
			}
			set
			{
				if ((this._discount_val != value))
				{
					this.Ondiscount_valChanging(value);
					this.SendPropertyChanging();
					this._discount_val = value;
					this.SendPropertyChanged("discount_val");
					this.Ondiscount_valChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tax_val", DbType="Float")]
		public System.Nullable<double> Tax_val
		{
			get
			{
				return this._Tax_val;
			}
			set
			{
				if ((this._Tax_val != value))
				{
					this.OnTax_valChanging(value);
					this.SendPropertyChanging();
					this._Tax_val = value;
					this.SendPropertyChanged("Tax_val");
					this.OnTax_valChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_final_cost", DbType="Float")]
		public System.Nullable<double> final_cost
		{
			get
			{
				return this._final_cost;
			}
			set
			{
				if ((this._final_cost != value))
				{
					this.Onfinal_costChanging(value);
					this.SendPropertyChanging();
					this._final_cost = value;
					this.SendPropertyChanged("final_cost");
					this.Onfinal_costChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment", DbType="NChar(50)")]
		public string payment
		{
			get
			{
				return this._payment;
			}
			set
			{
				if ((this._payment != value))
				{
					this.OnpaymentChanging(value);
					this.SendPropertyChanging();
					this._payment = value;
					this.SendPropertyChanged("payment");
					this.OnpaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Order_item_order", Storage="_Tbl_Order", ThisKey="order_id", OtherKey="ID", IsForeignKey=true)]
		public Tbl_Order Tbl_Order
		{
			get
			{
				return this._Tbl_Order.Entity;
			}
			set
			{
				Tbl_Order previousValue = this._Tbl_Order.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Order.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Order.Entity = null;
						previousValue.item_orders.Remove(this);
					}
					this._Tbl_Order.Entity = value;
					if ((value != null))
					{
						value.item_orders.Add(this);
						this._order_id = value.ID;
					}
					else
					{
						this._order_id = default(int);
					}
					this.SendPropertyChanged("Tbl_Order");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblItem_item_order", Storage="_TblItem", ThisKey="item_id", OtherKey="ID", IsForeignKey=true)]
		public TblItem TblItem
		{
			get
			{
				return this._TblItem.Entity;
			}
			set
			{
				TblItem previousValue = this._TblItem.Entity;
				if (((previousValue != value) 
							|| (this._TblItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblItem.Entity = null;
						previousValue.item_orders.Remove(this);
					}
					this._TblItem.Entity = value;
					if ((value != null))
					{
						value.item_orders.Add(this);
						this._item_id = value.ID;
					}
					else
					{
						this._item_id = default(int);
					}
					this.SendPropertyChanged("TblItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TablePlace")]
	public partial class TablePlace : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Tableplace1;
		
		private EntityRef<TBLTable> _TBLTable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTableplace1Changing(string value);
    partial void OnTableplace1Changed();
    #endregion
		
		public TablePlace()
		{
			this._TBLTable = default(EntityRef<TBLTable>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Tableplace", Storage="_Tableplace1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tableplace1
		{
			get
			{
				return this._Tableplace1;
			}
			set
			{
				if ((this._Tableplace1 != value))
				{
					this.OnTableplace1Changing(value);
					this.SendPropertyChanging();
					this._Tableplace1 = value;
					this.SendPropertyChanged("Tableplace1");
					this.OnTableplace1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TablePlace_TBLTable", Storage="_TBLTable", ThisKey="ID", OtherKey="ID", IsUnique=true, IsForeignKey=false)]
		public TBLTable TBLTable
		{
			get
			{
				return this._TBLTable.Entity;
			}
			set
			{
				TBLTable previousValue = this._TBLTable.Entity;
				if (((previousValue != value) 
							|| (this._TBLTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLTable.Entity = null;
						previousValue.TablePlace = null;
					}
					this._TBLTable.Entity = value;
					if ((value != null))
					{
						value.TablePlace = this;
					}
					this.SendPropertyChanged("TBLTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Casheir_Sale")]
	public partial class Tbl_Casheir_Sale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Item_Name;
		
		private System.Nullable<double> _Item_Price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnItem_NameChanging(string value);
    partial void OnItem_NameChanged();
    partial void OnItem_PriceChanging(System.Nullable<double> value);
    partial void OnItem_PriceChanged();
    #endregion
		
		public Tbl_Casheir_Sale()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Name", DbType="NVarChar(50)")]
		public string Item_Name
		{
			get
			{
				return this._Item_Name;
			}
			set
			{
				if ((this._Item_Name != value))
				{
					this.OnItem_NameChanging(value);
					this.SendPropertyChanging();
					this._Item_Name = value;
					this.SendPropertyChanged("Item_Name");
					this.OnItem_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Price", DbType="Float")]
		public System.Nullable<double> Item_Price
		{
			get
			{
				return this._Item_Price;
			}
			set
			{
				if ((this._Item_Price != value))
				{
					this.OnItem_PriceChanging(value);
					this.SendPropertyChanging();
					this._Item_Price = value;
					this.SendPropertyChanged("Item_Price");
					this.OnItem_PriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Daily_operation")]
	public partial class Tbl_Daily_operation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _Item_Code;
		
		private string _Item_Name;
		
		private System.Nullable<int> _Quantity_Number;
		
		private System.Nullable<double> _Packu_Price;
		
		private System.Nullable<double> _Total_Cost;
		
		private System.Nullable<System.DateTime> _Import_Date;
		
		private System.Nullable<int> _receipt_Code;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnItem_CodeChanging(System.Nullable<int> value);
    partial void OnItem_CodeChanged();
    partial void OnItem_NameChanging(string value);
    partial void OnItem_NameChanged();
    partial void OnQuantity_NumberChanging(System.Nullable<int> value);
    partial void OnQuantity_NumberChanged();
    partial void OnPacku_PriceChanging(System.Nullable<double> value);
    partial void OnPacku_PriceChanged();
    partial void OnTotal_CostChanging(System.Nullable<double> value);
    partial void OnTotal_CostChanged();
    partial void OnImport_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnImport_DateChanged();
    partial void Onreceipt_CodeChanging(System.Nullable<int> value);
    partial void Onreceipt_CodeChanged();
    #endregion
		
		public Tbl_Daily_operation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Code", DbType="Int")]
		public System.Nullable<int> Item_Code
		{
			get
			{
				return this._Item_Code;
			}
			set
			{
				if ((this._Item_Code != value))
				{
					this.OnItem_CodeChanging(value);
					this.SendPropertyChanging();
					this._Item_Code = value;
					this.SendPropertyChanged("Item_Code");
					this.OnItem_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Name", DbType="NVarChar(50)")]
		public string Item_Name
		{
			get
			{
				return this._Item_Name;
			}
			set
			{
				if ((this._Item_Name != value))
				{
					this.OnItem_NameChanging(value);
					this.SendPropertyChanging();
					this._Item_Name = value;
					this.SendPropertyChanged("Item_Name");
					this.OnItem_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity_Number", DbType="Int")]
		public System.Nullable<int> Quantity_Number
		{
			get
			{
				return this._Quantity_Number;
			}
			set
			{
				if ((this._Quantity_Number != value))
				{
					this.OnQuantity_NumberChanging(value);
					this.SendPropertyChanging();
					this._Quantity_Number = value;
					this.SendPropertyChanged("Quantity_Number");
					this.OnQuantity_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Packu_Price", DbType="Float")]
		public System.Nullable<double> Packu_Price
		{
			get
			{
				return this._Packu_Price;
			}
			set
			{
				if ((this._Packu_Price != value))
				{
					this.OnPacku_PriceChanging(value);
					this.SendPropertyChanging();
					this._Packu_Price = value;
					this.SendPropertyChanged("Packu_Price");
					this.OnPacku_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Cost", DbType="Float")]
		public System.Nullable<double> Total_Cost
		{
			get
			{
				return this._Total_Cost;
			}
			set
			{
				if ((this._Total_Cost != value))
				{
					this.OnTotal_CostChanging(value);
					this.SendPropertyChanging();
					this._Total_Cost = value;
					this.SendPropertyChanged("Total_Cost");
					this.OnTotal_CostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Import_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Import_Date
		{
			get
			{
				return this._Import_Date;
			}
			set
			{
				if ((this._Import_Date != value))
				{
					this.OnImport_DateChanging(value);
					this.SendPropertyChanging();
					this._Import_Date = value;
					this.SendPropertyChanged("Import_Date");
					this.OnImport_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_Code", DbType="Int")]
		public System.Nullable<int> receipt_Code
		{
			get
			{
				return this._receipt_Code;
			}
			set
			{
				if ((this._receipt_Code != value))
				{
					this.Onreceipt_CodeChanging(value);
					this.SendPropertyChanging();
					this._receipt_Code = value;
					this.SendPropertyChanged("receipt_Code");
					this.Onreceipt_CodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Import")]
	public partial class Tbl_Import : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _receipt_Code;
		
		private System.Nullable<System.DateTime> _Import_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onreceipt_CodeChanging(System.Nullable<int> value);
    partial void Onreceipt_CodeChanged();
    partial void OnImport_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnImport_DateChanged();
    #endregion
		
		public Tbl_Import()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_Code", DbType="Int")]
		public System.Nullable<int> receipt_Code
		{
			get
			{
				return this._receipt_Code;
			}
			set
			{
				if ((this._receipt_Code != value))
				{
					this.Onreceipt_CodeChanging(value);
					this.SendPropertyChanging();
					this._receipt_Code = value;
					this.SendPropertyChanged("receipt_Code");
					this.Onreceipt_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Import_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Import_Date
		{
			get
			{
				return this._Import_Date;
			}
			set
			{
				if ((this._Import_Date != value))
				{
					this.OnImport_DateChanging(value);
					this.SendPropertyChanging();
					this._Import_Date = value;
					this.SendPropertyChanged("Import_Date");
					this.OnImport_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Item_Price")]
	public partial class TBL_Item_Price : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _Item_Code;
		
		private string _Item_Name;
		
		private System.Nullable<decimal> _Purchase_Price;
		
		private System.Nullable<decimal> _Sale_Price;
		
		private System.Nullable<System.DateTime> _Validation_Date;
		
		private System.Nullable<System.DateTime> _Receive_Date;
		
		private System.Nullable<int> _receipt_Number;
		
		private EntityRef<TBL_Receive> _TBL_Receive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnItem_CodeChanging(System.Nullable<int> value);
    partial void OnItem_CodeChanged();
    partial void OnItem_NameChanging(string value);
    partial void OnItem_NameChanged();
    partial void OnPurchase_PriceChanging(System.Nullable<decimal> value);
    partial void OnPurchase_PriceChanged();
    partial void OnSale_PriceChanging(System.Nullable<decimal> value);
    partial void OnSale_PriceChanged();
    partial void OnValidation_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnValidation_DateChanged();
    partial void OnReceive_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnReceive_DateChanged();
    partial void Onreceipt_NumberChanging(System.Nullable<int> value);
    partial void Onreceipt_NumberChanged();
    #endregion
		
		public TBL_Item_Price()
		{
			this._TBL_Receive = default(EntityRef<TBL_Receive>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._TBL_Receive.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Code", DbType="Int")]
		public System.Nullable<int> Item_Code
		{
			get
			{
				return this._Item_Code;
			}
			set
			{
				if ((this._Item_Code != value))
				{
					this.OnItem_CodeChanging(value);
					this.SendPropertyChanging();
					this._Item_Code = value;
					this.SendPropertyChanged("Item_Code");
					this.OnItem_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Name", DbType="NVarChar(50)")]
		public string Item_Name
		{
			get
			{
				return this._Item_Name;
			}
			set
			{
				if ((this._Item_Name != value))
				{
					this.OnItem_NameChanging(value);
					this.SendPropertyChanging();
					this._Item_Name = value;
					this.SendPropertyChanged("Item_Name");
					this.OnItem_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Purchase_Price", DbType="Money")]
		public System.Nullable<decimal> Purchase_Price
		{
			get
			{
				return this._Purchase_Price;
			}
			set
			{
				if ((this._Purchase_Price != value))
				{
					this.OnPurchase_PriceChanging(value);
					this.SendPropertyChanging();
					this._Purchase_Price = value;
					this.SendPropertyChanged("Purchase_Price");
					this.OnPurchase_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sale_Price", DbType="Money")]
		public System.Nullable<decimal> Sale_Price
		{
			get
			{
				return this._Sale_Price;
			}
			set
			{
				if ((this._Sale_Price != value))
				{
					this.OnSale_PriceChanging(value);
					this.SendPropertyChanging();
					this._Sale_Price = value;
					this.SendPropertyChanged("Sale_Price");
					this.OnSale_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Validation_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Validation_Date
		{
			get
			{
				return this._Validation_Date;
			}
			set
			{
				if ((this._Validation_Date != value))
				{
					this.OnValidation_DateChanging(value);
					this.SendPropertyChanging();
					this._Validation_Date = value;
					this.SendPropertyChanged("Validation_Date");
					this.OnValidation_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Receive_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Receive_Date
		{
			get
			{
				return this._Receive_Date;
			}
			set
			{
				if ((this._Receive_Date != value))
				{
					this.OnReceive_DateChanging(value);
					this.SendPropertyChanging();
					this._Receive_Date = value;
					this.SendPropertyChanged("Receive_Date");
					this.OnReceive_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_Number", DbType="Int")]
		public System.Nullable<int> receipt_Number
		{
			get
			{
				return this._receipt_Number;
			}
			set
			{
				if ((this._receipt_Number != value))
				{
					this.Onreceipt_NumberChanging(value);
					this.SendPropertyChanging();
					this._receipt_Number = value;
					this.SendPropertyChanged("receipt_Number");
					this.Onreceipt_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_Receive_TBL_Item_Price", Storage="_TBL_Receive", ThisKey="ID", OtherKey="ID", IsForeignKey=true)]
		public TBL_Receive TBL_Receive
		{
			get
			{
				return this._TBL_Receive.Entity;
			}
			set
			{
				TBL_Receive previousValue = this._TBL_Receive.Entity;
				if (((previousValue != value) 
							|| (this._TBL_Receive.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_Receive.Entity = null;
						previousValue.TBL_Item_Price = null;
					}
					this._TBL_Receive.Entity = value;
					if ((value != null))
					{
						value.TBL_Item_Price = this;
						this._ID = value.ID;
					}
					else
					{
						this._ID = default(int);
					}
					this.SendPropertyChanged("TBL_Receive");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_login")]
	public partial class Tbl_login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Password;
		
		private string _hint;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnhintChanging(string value);
    partial void OnhintChanged();
    #endregion
		
		public Tbl_login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hint", DbType="NVarChar(50)")]
		public string hint
		{
			get
			{
				return this._hint;
			}
			set
			{
				if ((this._hint != value))
				{
					this.OnhintChanging(value);
					this.SendPropertyChanging();
					this._hint = value;
					this.SendPropertyChanged("hint");
					this.OnhintChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Numbers")]
	public partial class TBL_Number : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _TBL_ID;
		
		private int _Numbers;
		
		private int _TBLPlace_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTBL_IDChanging(int value);
    partial void OnTBL_IDChanged();
    partial void OnNumbersChanging(int value);
    partial void OnNumbersChanged();
    partial void OnTBLPlace_IDChanging(int value);
    partial void OnTBLPlace_IDChanged();
    #endregion
		
		public TBL_Number()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBL_ID", DbType="Int NOT NULL")]
		public int TBL_ID
		{
			get
			{
				return this._TBL_ID;
			}
			set
			{
				if ((this._TBL_ID != value))
				{
					this.OnTBL_IDChanging(value);
					this.SendPropertyChanging();
					this._TBL_ID = value;
					this.SendPropertyChanged("TBL_ID");
					this.OnTBL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numbers", DbType="Int NOT NULL")]
		public int Numbers
		{
			get
			{
				return this._Numbers;
			}
			set
			{
				if ((this._Numbers != value))
				{
					this.OnNumbersChanging(value);
					this.SendPropertyChanging();
					this._Numbers = value;
					this.SendPropertyChanged("Numbers");
					this.OnNumbersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLPlace_ID", DbType="Int NOT NULL")]
		public int TBLPlace_ID
		{
			get
			{
				return this._TBLPlace_ID;
			}
			set
			{
				if ((this._TBLPlace_ID != value))
				{
					this.OnTBLPlace_IDChanging(value);
					this.SendPropertyChanging();
					this._TBLPlace_ID = value;
					this.SendPropertyChanged("TBLPlace_ID");
					this.OnTBLPlace_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Order")]
	public partial class Tbl_Order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _order_id;
		
		private int _item_id;
		
		private int _quantity;
		
		private double _price;
		
		private EntitySet<item_order> _item_orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onorder_idChanging(int value);
    partial void Onorder_idChanged();
    partial void Onitem_idChanging(int value);
    partial void Onitem_idChanged();
    partial void OnquantityChanging(int value);
    partial void OnquantityChanged();
    partial void OnpriceChanging(double value);
    partial void OnpriceChanged();
    #endregion
		
		public Tbl_Order()
		{
			this._item_orders = new EntitySet<item_order>(new Action<item_order>(this.attach_item_orders), new Action<item_order>(this.detach_item_orders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int NOT NULL")]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this.Onorder_idChanging(value);
					this.SendPropertyChanging();
					this._order_id = value;
					this.SendPropertyChanged("order_id");
					this.Onorder_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_id", DbType="Int NOT NULL")]
		public int item_id
		{
			get
			{
				return this._item_id;
			}
			set
			{
				if ((this._item_id != value))
				{
					this.Onitem_idChanging(value);
					this.SendPropertyChanging();
					this._item_id = value;
					this.SendPropertyChanged("item_id");
					this.Onitem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float NOT NULL")]
		public double price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Order_item_order", Storage="_item_orders", ThisKey="ID", OtherKey="order_id")]
		public EntitySet<item_order> item_orders
		{
			get
			{
				return this._item_orders;
			}
			set
			{
				this._item_orders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_item_orders(item_order entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Order = this;
		}
		
		private void detach_item_orders(item_order entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Order = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Receive")]
	public partial class TBL_Receive : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _recieve_num;
		
		private System.Nullable<System.DateTime> _recieve_Date;
		
		private EntityRef<TBL_Item_Price> _TBL_Item_Price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onrecieve_numChanging(int value);
    partial void Onrecieve_numChanged();
    partial void Onrecieve_DateChanging(System.Nullable<System.DateTime> value);
    partial void Onrecieve_DateChanged();
    #endregion
		
		public TBL_Receive()
		{
			this._TBL_Item_Price = default(EntityRef<TBL_Item_Price>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieve_num", DbType="Int NOT NULL")]
		public int recieve_num
		{
			get
			{
				return this._recieve_num;
			}
			set
			{
				if ((this._recieve_num != value))
				{
					this.Onrecieve_numChanging(value);
					this.SendPropertyChanging();
					this._recieve_num = value;
					this.SendPropertyChanged("recieve_num");
					this.Onrecieve_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieve_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> recieve_Date
		{
			get
			{
				return this._recieve_Date;
			}
			set
			{
				if ((this._recieve_Date != value))
				{
					this.Onrecieve_DateChanging(value);
					this.SendPropertyChanging();
					this._recieve_Date = value;
					this.SendPropertyChanged("recieve_Date");
					this.Onrecieve_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_Receive_TBL_Item_Price", Storage="_TBL_Item_Price", ThisKey="ID", OtherKey="ID", IsUnique=true, IsForeignKey=false)]
		public TBL_Item_Price TBL_Item_Price
		{
			get
			{
				return this._TBL_Item_Price.Entity;
			}
			set
			{
				TBL_Item_Price previousValue = this._TBL_Item_Price.Entity;
				if (((previousValue != value) 
							|| (this._TBL_Item_Price.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_Item_Price.Entity = null;
						previousValue.TBL_Receive = null;
					}
					this._TBL_Item_Price.Entity = value;
					if ((value != null))
					{
						value.TBL_Receive = this;
					}
					this.SendPropertyChanged("TBL_Item_Price");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblAddItem")]
	public partial class TblAddItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ItemName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnItemNameChanging(string value);
    partial void OnItemNameChanged();
    #endregion
		
		public TblAddItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ItemName
		{
			get
			{
				return this._ItemName;
			}
			set
			{
				if ((this._ItemName != value))
				{
					this.OnItemNameChanging(value);
					this.SendPropertyChanging();
					this._ItemName = value;
					this.SendPropertyChanged("ItemName");
					this.OnItemNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLChecks")]
	public partial class TBLCheck : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _Date;
		
		private string _Hall;
		
		private int _Tablenumber;
		
		private System.DateTime _Validationdate;
		
		private string _Cashier;
		
		private int _Checknumber;
		
		private string _Paymentmethod;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnHallChanging(string value);
    partial void OnHallChanged();
    partial void OnTablenumberChanging(int value);
    partial void OnTablenumberChanged();
    partial void OnValidationdateChanging(System.DateTime value);
    partial void OnValidationdateChanged();
    partial void OnCashierChanging(string value);
    partial void OnCashierChanged();
    partial void OnChecknumberChanging(int value);
    partial void OnChecknumberChanged();
    partial void OnPaymentmethodChanging(string value);
    partial void OnPaymentmethodChanged();
    #endregion
		
		public TBLCheck()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hall", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Hall
		{
			get
			{
				return this._Hall;
			}
			set
			{
				if ((this._Hall != value))
				{
					this.OnHallChanging(value);
					this.SendPropertyChanging();
					this._Hall = value;
					this.SendPropertyChanged("Hall");
					this.OnHallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tablenumber", DbType="Int NOT NULL")]
		public int Tablenumber
		{
			get
			{
				return this._Tablenumber;
			}
			set
			{
				if ((this._Tablenumber != value))
				{
					this.OnTablenumberChanging(value);
					this.SendPropertyChanging();
					this._Tablenumber = value;
					this.SendPropertyChanged("Tablenumber");
					this.OnTablenumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Validationdate", DbType="Date NOT NULL")]
		public System.DateTime Validationdate
		{
			get
			{
				return this._Validationdate;
			}
			set
			{
				if ((this._Validationdate != value))
				{
					this.OnValidationdateChanging(value);
					this.SendPropertyChanging();
					this._Validationdate = value;
					this.SendPropertyChanged("Validationdate");
					this.OnValidationdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cashier", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Cashier
		{
			get
			{
				return this._Cashier;
			}
			set
			{
				if ((this._Cashier != value))
				{
					this.OnCashierChanging(value);
					this.SendPropertyChanging();
					this._Cashier = value;
					this.SendPropertyChanged("Cashier");
					this.OnCashierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checknumber", DbType="Int NOT NULL")]
		public int Checknumber
		{
			get
			{
				return this._Checknumber;
			}
			set
			{
				if ((this._Checknumber != value))
				{
					this.OnChecknumberChanging(value);
					this.SendPropertyChanging();
					this._Checknumber = value;
					this.SendPropertyChanged("Checknumber");
					this.OnChecknumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paymentmethod", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Paymentmethod
		{
			get
			{
				return this._Paymentmethod;
			}
			set
			{
				if ((this._Paymentmethod != value))
				{
					this.OnPaymentmethodChanging(value);
					this.SendPropertyChanging();
					this._Paymentmethod = value;
					this.SendPropertyChanged("Paymentmethod");
					this.OnPaymentmethodChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblItem")]
	public partial class TblItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Item_Name;
		
		private int _QuantityInteger;
		
		private int _QuantityNumber;
		
		private double _Packu_Price;
		
		private double _CostPrice;
		
		private System.DateTime _ValidationDate;
		
		private double _TotalCost;
		
		private EntitySet<item_order> _item_orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnItem_NameChanging(string value);
    partial void OnItem_NameChanged();
    partial void OnQuantityIntegerChanging(int value);
    partial void OnQuantityIntegerChanged();
    partial void OnQuantityNumberChanging(int value);
    partial void OnQuantityNumberChanged();
    partial void OnPacku_PriceChanging(double value);
    partial void OnPacku_PriceChanged();
    partial void OnCostPriceChanging(double value);
    partial void OnCostPriceChanged();
    partial void OnValidationDateChanging(System.DateTime value);
    partial void OnValidationDateChanged();
    partial void OnTotalCostChanging(double value);
    partial void OnTotalCostChanged();
    #endregion
		
		public TblItem()
		{
			this._item_orders = new EntitySet<item_order>(new Action<item_order>(this.attach_item_orders), new Action<item_order>(this.detach_item_orders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Item_Name
		{
			get
			{
				return this._Item_Name;
			}
			set
			{
				if ((this._Item_Name != value))
				{
					this.OnItem_NameChanging(value);
					this.SendPropertyChanging();
					this._Item_Name = value;
					this.SendPropertyChanged("Item_Name");
					this.OnItem_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantityInteger", DbType="Int NOT NULL")]
		public int QuantityInteger
		{
			get
			{
				return this._QuantityInteger;
			}
			set
			{
				if ((this._QuantityInteger != value))
				{
					this.OnQuantityIntegerChanging(value);
					this.SendPropertyChanging();
					this._QuantityInteger = value;
					this.SendPropertyChanged("QuantityInteger");
					this.OnQuantityIntegerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantityNumber", DbType="Int NOT NULL")]
		public int QuantityNumber
		{
			get
			{
				return this._QuantityNumber;
			}
			set
			{
				if ((this._QuantityNumber != value))
				{
					this.OnQuantityNumberChanging(value);
					this.SendPropertyChanging();
					this._QuantityNumber = value;
					this.SendPropertyChanged("QuantityNumber");
					this.OnQuantityNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Packu_Price", DbType="Float NOT NULL")]
		public double Packu_Price
		{
			get
			{
				return this._Packu_Price;
			}
			set
			{
				if ((this._Packu_Price != value))
				{
					this.OnPacku_PriceChanging(value);
					this.SendPropertyChanging();
					this._Packu_Price = value;
					this.SendPropertyChanged("Packu_Price");
					this.OnPacku_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostPrice", DbType="Float NOT NULL")]
		public double CostPrice
		{
			get
			{
				return this._CostPrice;
			}
			set
			{
				if ((this._CostPrice != value))
				{
					this.OnCostPriceChanging(value);
					this.SendPropertyChanging();
					this._CostPrice = value;
					this.SendPropertyChanged("CostPrice");
					this.OnCostPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidationDate", DbType="DateTime NOT NULL")]
		public System.DateTime ValidationDate
		{
			get
			{
				return this._ValidationDate;
			}
			set
			{
				if ((this._ValidationDate != value))
				{
					this.OnValidationDateChanging(value);
					this.SendPropertyChanging();
					this._ValidationDate = value;
					this.SendPropertyChanged("ValidationDate");
					this.OnValidationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalCost", DbType="Float NOT NULL")]
		public double TotalCost
		{
			get
			{
				return this._TotalCost;
			}
			set
			{
				if ((this._TotalCost != value))
				{
					this.OnTotalCostChanging(value);
					this.SendPropertyChanging();
					this._TotalCost = value;
					this.SendPropertyChanged("TotalCost");
					this.OnTotalCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblItem_item_order", Storage="_item_orders", ThisKey="ID", OtherKey="item_id")]
		public EntitySet<item_order> item_orders
		{
			get
			{
				return this._item_orders;
			}
			set
			{
				this._item_orders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_item_orders(item_order entity)
		{
			this.SendPropertyChanging();
			entity.TblItem = this;
		}
		
		private void detach_item_orders(item_order entity)
		{
			this.SendPropertyChanging();
			entity.TblItem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLTables")]
	public partial class TBLTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _SeaTables;
		
		private System.Nullable<int> _ShlalTables;
		
		private System.Nullable<int> _RestaurantTables;
		
		private System.Nullable<int> _CoffeeTables;
		
		private EntityRef<TablePlace> _TablePlace;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSeaTablesChanging(System.Nullable<int> value);
    partial void OnSeaTablesChanged();
    partial void OnShlalTablesChanging(System.Nullable<int> value);
    partial void OnShlalTablesChanged();
    partial void OnRestaurantTablesChanging(System.Nullable<int> value);
    partial void OnRestaurantTablesChanged();
    partial void OnCoffeeTablesChanging(System.Nullable<int> value);
    partial void OnCoffeeTablesChanged();
    #endregion
		
		public TBLTable()
		{
			this._TablePlace = default(EntityRef<TablePlace>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._TablePlace.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeaTables", DbType="Int")]
		public System.Nullable<int> SeaTables
		{
			get
			{
				return this._SeaTables;
			}
			set
			{
				if ((this._SeaTables != value))
				{
					this.OnSeaTablesChanging(value);
					this.SendPropertyChanging();
					this._SeaTables = value;
					this.SendPropertyChanged("SeaTables");
					this.OnSeaTablesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShlalTables", DbType="Int")]
		public System.Nullable<int> ShlalTables
		{
			get
			{
				return this._ShlalTables;
			}
			set
			{
				if ((this._ShlalTables != value))
				{
					this.OnShlalTablesChanging(value);
					this.SendPropertyChanging();
					this._ShlalTables = value;
					this.SendPropertyChanged("ShlalTables");
					this.OnShlalTablesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RestaurantTables", DbType="Int")]
		public System.Nullable<int> RestaurantTables
		{
			get
			{
				return this._RestaurantTables;
			}
			set
			{
				if ((this._RestaurantTables != value))
				{
					this.OnRestaurantTablesChanging(value);
					this.SendPropertyChanging();
					this._RestaurantTables = value;
					this.SendPropertyChanged("RestaurantTables");
					this.OnRestaurantTablesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoffeeTables", DbType="Int")]
		public System.Nullable<int> CoffeeTables
		{
			get
			{
				return this._CoffeeTables;
			}
			set
			{
				if ((this._CoffeeTables != value))
				{
					this.OnCoffeeTablesChanging(value);
					this.SendPropertyChanging();
					this._CoffeeTables = value;
					this.SendPropertyChanged("CoffeeTables");
					this.OnCoffeeTablesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TablePlace_TBLTable", Storage="_TablePlace", ThisKey="ID", OtherKey="ID", IsForeignKey=true)]
		public TablePlace TablePlace
		{
			get
			{
				return this._TablePlace.Entity;
			}
			set
			{
				TablePlace previousValue = this._TablePlace.Entity;
				if (((previousValue != value) 
							|| (this._TablePlace.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TablePlace.Entity = null;
						previousValue.TBLTable = null;
					}
					this._TablePlace.Entity = value;
					if ((value != null))
					{
						value.TBLTable = this;
						this._ID = value.ID;
					}
					else
					{
						this._ID = default(int);
					}
					this.SendPropertyChanged("TablePlace");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLCoffee")]
	public partial class TBLCoffee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _TBLNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTBLNumberChanging(System.Nullable<int> value);
    partial void OnTBLNumberChanged();
    #endregion
		
		public TBLCoffee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLNumber", DbType="Int")]
		public System.Nullable<int> TBLNumber
		{
			get
			{
				return this._TBLNumber;
			}
			set
			{
				if ((this._TBLNumber != value))
				{
					this.OnTBLNumberChanging(value);
					this.SendPropertyChanging();
					this._TBLNumber = value;
					this.SendPropertyChanged("TBLNumber");
					this.OnTBLNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLRestaurant")]
	public partial class TBLRestaurant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _TBLNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTBLNumberChanging(System.Nullable<int> value);
    partial void OnTBLNumberChanged();
    #endregion
		
		public TBLRestaurant()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLNumber", DbType="Int")]
		public System.Nullable<int> TBLNumber
		{
			get
			{
				return this._TBLNumber;
			}
			set
			{
				if ((this._TBLNumber != value))
				{
					this.OnTBLNumberChanging(value);
					this.SendPropertyChanging();
					this._TBLNumber = value;
					this.SendPropertyChanged("TBLNumber");
					this.OnTBLNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLSea")]
	public partial class TBLSea : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _TBLNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTBLNumberChanging(System.Nullable<int> value);
    partial void OnTBLNumberChanged();
    #endregion
		
		public TBLSea()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLNumber", DbType="Int")]
		public System.Nullable<int> TBLNumber
		{
			get
			{
				return this._TBLNumber;
			}
			set
			{
				if ((this._TBLNumber != value))
				{
					this.OnTBLNumberChanging(value);
					this.SendPropertyChanging();
					this._TBLNumber = value;
					this.SendPropertyChanged("TBLNumber");
					this.OnTBLNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblShlal")]
	public partial class TblShlal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _TBLNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTBLNumberChanging(int value);
    partial void OnTBLNumberChanged();
    #endregion
		
		public TblShlal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLNumber", DbType="Int NOT NULL")]
		public int TBLNumber
		{
			get
			{
				return this._TBLNumber;
			}
			set
			{
				if ((this._TBLNumber != value))
				{
					this.OnTBLNumberChanging(value);
					this.SendPropertyChanging();
					this._TBLNumber = value;
					this.SendPropertyChanged("TBLNumber");
					this.OnTBLNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class report_item_orderResult
	{
		
		private int _order_id;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _tablename;
		
		private System.Nullable<int> _tablenumber;
		
		private System.Nullable<double> _discount_val;
		
		private System.Nullable<double> _Tax_val;
		
		private string _payment;
		
		private System.Nullable<double> _Column1;
		
		public report_item_orderResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int NOT NULL")]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this._order_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tablename", DbType="NVarChar(50)")]
		public string tablename
		{
			get
			{
				return this._tablename;
			}
			set
			{
				if ((this._tablename != value))
				{
					this._tablename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tablenumber", DbType="Int")]
		public System.Nullable<int> tablenumber
		{
			get
			{
				return this._tablenumber;
			}
			set
			{
				if ((this._tablenumber != value))
				{
					this._tablenumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_val", DbType="Float")]
		public System.Nullable<double> discount_val
		{
			get
			{
				return this._discount_val;
			}
			set
			{
				if ((this._discount_val != value))
				{
					this._discount_val = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tax_val", DbType="Float")]
		public System.Nullable<double> Tax_val
		{
			get
			{
				return this._Tax_val;
			}
			set
			{
				if ((this._Tax_val != value))
				{
					this._Tax_val = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment", DbType="NChar(50)")]
		public string payment
		{
			get
			{
				return this._payment;
			}
			set
			{
				if ((this._payment != value))
				{
					this._payment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Float")]
		public System.Nullable<double> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class report_order_detailsResult
	{
		
		private int _order_id;
		
		private string _Item_Name;
		
		private int _quantity;
		
		private double _price;
		
		public report_order_detailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int NOT NULL")]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this._order_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Item_Name
		{
			get
			{
				return this._Item_Name;
			}
			set
			{
				if ((this._Item_Name != value))
				{
					this._Item_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this._quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float NOT NULL")]
		public double price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
	}
	
	public partial class report_tbl_numResult
	{
		
		private System.Nullable<int> _tablenumber;
		
		public report_tbl_numResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tablenumber", DbType="Int")]
		public System.Nullable<int> tablenumber
		{
			get
			{
				return this._tablenumber;
			}
			set
			{
				if ((this._tablenumber != value))
				{
					this._tablenumber = value;
				}
			}
		}
	}
	
	public partial class selectallResult
	{
		
		private int _ID;
		
		private int _item_id;
		
		private int _order_id;
		
		private double _total_cost;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _TBL_Num;
		
		private System.Nullable<double> _discount_val;
		
		private System.Nullable<double> _Tax_val;
		
		private System.Nullable<double> _final_cost;
		
		private string _payment;
		
		public selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_id", DbType="Int NOT NULL")]
		public int item_id
		{
			get
			{
				return this._item_id;
			}
			set
			{
				if ((this._item_id != value))
				{
					this._item_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int NOT NULL")]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this._order_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_cost", DbType="Float NOT NULL")]
		public double total_cost
		{
			get
			{
				return this._total_cost;
			}
			set
			{
				if ((this._total_cost != value))
				{
					this._total_cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBL_Num", DbType="Int")]
		public System.Nullable<int> TBL_Num
		{
			get
			{
				return this._TBL_Num;
			}
			set
			{
				if ((this._TBL_Num != value))
				{
					this._TBL_Num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_val", DbType="Float")]
		public System.Nullable<double> discount_val
		{
			get
			{
				return this._discount_val;
			}
			set
			{
				if ((this._discount_val != value))
				{
					this._discount_val = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tax_val", DbType="Float")]
		public System.Nullable<double> Tax_val
		{
			get
			{
				return this._Tax_val;
			}
			set
			{
				if ((this._Tax_val != value))
				{
					this._Tax_val = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_final_cost", DbType="Float")]
		public System.Nullable<double> final_cost
		{
			get
			{
				return this._final_cost;
			}
			set
			{
				if ((this._final_cost != value))
				{
					this._final_cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment", DbType="NChar(50)")]
		public string payment
		{
			get
			{
				return this._payment;
			}
			set
			{
				if ((this._payment != value))
				{
					this._payment = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
